name: Sementic Release

on:
  pull_request:
    types: [closed]
  #push:
  #  branches: [ "main" ]

env:
  ENV_FILE: .github/version.env

jobs:

  determine-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      SKIP_VERSION_UPDATE: ${{ steps.determine-version.outputs.SKIP_VERSION_UPDATE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Load current version
      id: load-version
      run: |
        if [ -f "$ENV_FILE" ]; then
          source $ENV_FILE
          echo "Current version: $VERSION"
        else
          # Datei existiert nicht, also erstellen wir sie
          echo "Creating $ENV_FILE, as it doesn't exist."
          touch $ENV_FILE
          echo "VERSION=0.0.0" > $ENV_FILE
          source $ENV_FILE
          echo "Initialized VERSION to 0.0.0"
        fi

        # Überprüfen, ob die Variable VERSION existiert, wenn nicht, hinzufügen
        if ! grep -q "^VERSION=" "$ENV_FILE"; then
          echo "VERSION=0.0.0" >> $ENV_FILE
          echo "Added VERSION to $ENV_FILE"
        fi

        echo "VERSION=$VERSION" >> $GITHUB_ENV                        

    - name: Determine new version
      id: determine-version
      run: |
        # Aktuelle Version laden
        IFS='.' read -r MAJOR MINOR PATCH <<< "${VERSION:-0.0.0}"

        # Typ des Pull Requests analysieren
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"
        
        echo "PR Title: $PR_TITLE"
        echo "PR Body: $PR_BODY"

        # Check to skip or not
        SKIP_UPDATE='true'
        # Ignoriere PRs mit "test" im Titel
        if [[ "$PR_TITLE" == "test:"* ]]; then
          echo "Skipping version update for test-related PR."
          echo "SKIP_VERSION_UPDATE=$SKIP_UPDATE" >> $GITHUB_OUTPUT  
          exit 0
        fi

        # Ignoriere PRs mit "docs" im Titel
        if [[ "$PR_TITLE" == "docs:"* ]]; then
          echo "Skipping version update for docs-related PR."
          echo "SKIP_VERSION_UPDATE=$SKIP_UPDATE" >> $GITHUB_OUTPUT  
          exit 0
        fi

        echo "SKIP_VERSION_UPDATE=false" >> $GITHUB_OUTPUT 

        # Standardmäßig Patch erhöhen
        NEW_MAJOR=$MAJOR
        NEW_MINOR=$MINOR
        NEW_PATCH=$((PATCH + 1))

        # Prüfe, ob der Titel spezifische Schlüsselwörter enthält
        if [[ "$PR_TITLE" == "breaking-change:"* ]]; then
          # Breaking Change -> Major erhöhen
          NEW_MAJOR=$((MAJOR + 1))
          NEW_MINOR=0
          NEW_PATCH=0
          TYPE=breaking-change
        elif [[ "$PR_TITLE" == "feat:"* ]]; then
          # Feature -> Minor erhöhen
          NEW_MINOR=$((MINOR + 1))
          NEW_PATCH=0
          TYPE=feat
        elif [[ "$PR_TITLE" == *"fix:"* ]]; then
          # Fix -> Patch erhöhen (Standard)
          NEW_PATCH=$((PATCH + 1))
          TYPE=fix
        else
          echo "WARNING: PR does not specify change type, assuming patch."
          TYPE=Unknown
        fi

        # Neue Version zusammenstellen
        NEW_VERSION="$NEW_MAJOR.$NEW_MINOR.$NEW_PATCH"
        echo "New version: $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "Type: $TYPE"

        # Version in ENV-Datei aktualisieren
        echo "VERSION=$NEW_VERSION" > $ENV_FILE
        cat $ENV_FILE                        

    - name: Commit and push updated version
      run: |
        if [[ ${{ steps.determine-version.outputs.SKIP_VERSION_UPDATE }} == 'true' ]]; then
          echo "Skipped."
          exit 0;
        fi

        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add $ENV_FILE
        git commit -m "Update version to ${{ env.NEW_VERSION }}"
        git push origin main                        

  create-tag:
    runs-on: "ubuntu-latest"
    needs: "determine-version"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Create and push new tag
      run: |
        source $ENV_FILE
        
        if [[ ${{ needs.determine-version.outputs.SKIP_VERSION_UPDATE }} == 'true' ]]; then
          echo Create and push new tag is skipped
          exit 0;
        fi
        
        AUTH_HEADER="authorization: Basic $(echo -n "${{ secrets.API_USERNAME }}:${{ secrets.API_TOKEN }}" | base64)"

        RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X 'POST' \
          "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/tags" \
          -H 'accept: application/json' \
          -H "$AUTH_HEADER" \
          -H 'Content-Type: application/json' \
          -d "{\"message\": \"Created by ${{ github.actor }}\",\"tag_name\": \"${VERSION}\",\"target\": \"main\"}")

        # Prüfen des Statuscodes
        if [ "$RESPONSE" -eq 201 ]; then
          echo "Tag successfully created! HTTP Status: $RESPONSE"
          echo "Response:"
          cat response.json
        else
          echo "Failed to create tag. HTTP Status: $RESPONSE"
          echo "Response:"
          cat response.json
          exit 1
        fi
                                      

