name: Reusable workflow

#Upload Nuget Package to Package Source

on:
  push:
    branches-ignore: [ "main", "test/*" ]
    # Pattern matched against refs/tags
    #tags:
    #  - '*'     # Push events to every tag not containing /
env:
  ENV_FILE: .github/version.env

jobs:

  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo " The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - run: env
      - run: ls ./
      - name: Check out repository code
        uses: actions/checkout@v4

  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:

    - uses: actions/checkout@v4
    - id: set-version # important for output, need same name 
      run: |
        source $ENV_FILE
        NEW_APP_VERSION="$VERSION-${{ github.run_id }}"
        echo "version=$NEW_APP_VERSION" >> $GITHUB_OUTPUT                
      
  get-version:
    needs: set-version
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ needs.set-version.outputs.version }}
      
  call-workflow-in-local-repo:
    uses: ./.github/workflows/jobs/create-package-helm.yml
    needs: set-version
    with:
      prefix: ${{ vars.PREFIX }}
      version: ${{ needs.set-version.outputs.version }}
      helm-source: ${{ secrets.HELM_SOURCE }}
      api-username: ${{ secrets.API_USERNAME }}
      api-token: ${{ secrets.API_TOKEN }}
      path: ${{ vars.PATH }}
      release-name: "preview"